server:
 port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # If we write this line, then we don't need the followings

#      routes:
#        - id: currency-conversion
#          uri: lb://currency-conversion
#          predicates:
#          - Path=/**